### ISSUE TITLE
MQTT discovery not working

### ISSUE THREAD

**Issue by aptonline** [lanrat/hass-screenshot#1]
I've manually built and installed the docker image and have it running and connected to my MQTT server and I can see it's reporting to both the web interface and to the MQTT server as I can see it in MQTT.fx.

```
{
  "Unknown Device": {
    "name": "Unknown Device",
    "ip": "x.x.x.x",
    "mac_address": "x.x.x.x",
    "serial_number": "x.x.x.x",
    "boot_time": 1584482200,
    "wifi_signal": -50,
    "count": 175,
    "battery_level": 96,
    "charging": false,
    "last_seen": "2022-05-15T09:34:31.997Z",
    "update_interval": 1211
  }
}
```

![Screenshot 2022-05-15 at 11 05 55](https://user-images.githubusercontent.com/190136/168467436-fc550c2e-b107-469d-8812-f7f2fe16460d.png)

Within Home Assistant MQTT is enabled and connected to my server and my understanding is MQTT discovery is enabled by default and should show as a notification for setup but home assistant is not seeing hass-screenshot.

**Comment by aptonline** [comment]
Any ideas @lanrat ?

**Comment by lanrat** [comment]
If you are seeing the correct data in your MQTT server, then the issue is somewhere between Home Assistant and your MQTT server.

Do you have the MQTT integration set to automatically add new devices?
<img width="476" alt="Screen Shot 2022-05-20 at 3 20 57 PM" src="https://user-images.githubusercontent.com/164192/169619747-8a0c9631-7f95-4fe6-a423-84cc654ea8e2.png">

Are there any errors being printed in the Home Assistant console?

Another thought: I've never tested using a device name with a space in it. Could you rey renaming your device to not have a space and see if that helps?

**Comment by aptonline** [comment]
No errors in HA and yes I have enable newly added entries enabled.

I’m leaning towards that it may be device name related as in another issue I raised mentioned that the name is showing as “unknown device” and to your point this has a space in it.

Will give that a try.

**Comment by aptonline** [comment]
Confirmed that setting the Kindle name without spaces resolved the issue and is now showing in Home Assistant so thanks for pointing me in the right direction.

I was setting the name under `Defaults` and not under `Device Specific Overrides` and setting the MAC address suffix to the Kindle in use.

**Comment by lanrat** [comment]
Glad to hear it.

I just updated the default name to no longer use a space to prevent this issue in the future.
